# -*- coding: utf-8 -*-
"""Rule base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cq9JilvrM6ZLqxpqfleFy9xfEgO1CDBf
"""

!pip install -q requests
!pip install -q bs4
!pip install -q html2text
!pip install -q chromadb
!pip install -q google-generativeai

from google.colab import drive
drive.mount('/content/drive')

!pip install streamlit
!pip install chromadb
!pip install google-generativeai
!pip install torch torchvision torchaudio
!pip install sentence-transformers
!pip install beautifulsoup4 requests # cho crawl nếu cần tích hợp

import uuid
from datetime import date
import hashlib
import re
import json
import html2text

import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urlparse

import chromadb
from chromadb.utils import embedding_functions
import google.generativeai as genai

# ================== DANH SÁCH URL THƯỜNG TRÚ (DVC)==================
THUONG_TRU_URLS = [
    {"procedure_code": "1.004222", "url": "https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc=1.004222"}
]

# ================== DANH SÁCH URL TẠM TRÚ (DVC) ==================
TAM_TRU_URLS = [
    {"procedure_code": "1.004194", "url": "https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc=1.004194"},###
    {"procedure_code": "1.002755", "url": "https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc=1.002755"},###
    {"procedure_code": "1.010028", "url": "https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc=1.010028"},###
]

# ================== DANH SÁCH URL THƯỜNG TRÚ (BCA) ==================
THUONG_TRU_BCA_URLS = [
    {"procedure_code": "26360", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26360"},###
    {"procedure_code": "26348", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26348"},###
]

# ================== DANH SÁCH URL TẠM TRÚ (BCA) ==================
TAM_TRU_BCA_URLS = [
    {"procedure_code": "26356", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26356"},###
    {"procedure_code": "26552", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26552"},###
    {"procedure_code": "26345", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26345"},###
]

# ================== DANH SÁCH URL KHAI BÁO ==================
KHAI_BAO_THONG_TIN_URLS = [
    {"procedure_code": "26492", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26492"}
]

# ================== DANH SÁCH URL ĐIỀU CHỈNH ==================
DIEU_CHINH_THONG_TIN_CU_TRU_URLS = [
    {"procedure_code": "26498", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26498"}
]

# ================== DANH SÁCH URL KHAI BÁO TẠM VẮNG ==================
KHAI_BAO_TAM_VANG_URLS = [
    {"procedure_code": "26351", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26351"}
]

# ================== DANH SÁCH URL TÁCH HỘ ==================
TACH_HO_URLS = [
    {"procedure_code": "26499", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26499"}
]

# ================== DANH SÁCH URL THÔNG BÁO LƯU TRÚ ==================
LUU_TRU_URLS = [
    {"procedure_code": "26346", "url": "https://dichvucong.bocongan.gov.vn/bocongan/bothutuc/tthc?matt=26346"}
]

def clean_text(text):
    return re.sub(r'\s+', ' ', text).strip() if text else ""

def make_chunk(metadata, content, chunk_type, hierarchy, url, title, rows=0, cols=0):
    key = f"{url}{hierarchy}{content[:200]}"
    hash_id = hashlib.sha256(key.encode()).hexdigest()[:20]

    chunk = {
        "id": f"{hash_id}-{uuid.uuid4().hex[:8]}",
        "url": url,
        "title": title,
        "chunk_type": chunk_type,
        "hierarchy": hierarchy,
        "content_text": content.strip(),
        "metadata": {
            "source_domain": urlparse(url).netloc,
            "tokens": len(content.split()),
            "has_table": chunk_type == "table",
            "crawl_date": date.today().strftime("%Y-%m-%d"),
            "procedure_code": metadata.get("procedure_code", ""),
            "category": metadata.get("category", ""),
            "offical_annouce": "2196/QĐ-UBND ngày 19/6/2024",
            "is_entire": metadata.get("is_entire", False)
        }
    }
    if chunk_type == "table":
        chunk["metadata"].update({"row_count": rows, "col_count": cols})
    return chunk

def count_table_cells(table):
    rows = table.find_all("tr")
    cols = 0
    if rows:
        cols = len(rows[0].find_all(["th", "td"]))
    return len(rows), cols

def crawl_and_chunk(metadata, url, headers):
    resp = requests.get(url, headers=headers, timeout=20)
    resp.encoding = "utf-8"
    soup = BeautifulSoup(resp.text, "html.parser")

    title = clean_text(soup.h1.get_text()) if soup.h1 else "Không có tiêu đề"
    chunks = []
    hierarchy_stack = []
    h = html2text.HTML2Text()

    # Vùng nội dung chính của dichvucong
    main = soup.find("div", class_="row")
    if main:
        main = main.find("div", class_="col-sm-8")
    if not main:
        main = soup.body

    def should_skip(elem):
        if not elem.get("class"):
            return False
        classes = " ".join(elem["class"])
        skip_words = ["breadcrumb", "header", "footer", "navbar", "sidebar", "related", "comment"]
        return any(word in classes for word in skip_words)

    def process(elem):
        nonlocal hierarchy_stack

        if should_skip(elem):
            return False

        has_processed_child = False

        # Duyệt con trước
        for child in elem.children:
            if getattr(child, "name", None):
                if process(child):
                    has_processed_child = True

        # Xử lý chính element này
        # 1. Table
        if elem.name == "table" and not elem.get("data-processed"):
            md = h.handle(str(elem)).strip()
            if len(md) > 50:
                h_text = " > ".join(hierarchy_stack) or title
                rows, cols = count_table_cells(elem)
                chunks.append(make_chunk(metadata, md, "table", h_text, url, title, rows, cols))
                elem.attrs["data-processed"] = "true"
            return True

        # 2. List
        if elem.name in ["ul", "ol"]:
            items = [clean_text(li.get_text()) for li in elem.find_all("li", recursive=False)]
            if items:
                content = "\n- " + "\n- ".join(items)
                h_text = " > ".join(hierarchy_stack) or title
                chunks.append(make_chunk(metadata, content, "list", h_text, url, title))
            return True

        # 3. Heading
        if elem.name in ["h1", "h2", "h3", "h4", "h5", "h6"]:
            level = int(elem.name[1])
            text = clean_text(elem.get_text())
            if len(hierarchy_stack) >= level:
                hierarchy_stack[level-1] = text
                hierarchy_stack = hierarchy_stack[:level]
            else:
                hierarchy_stack.append(text)

            h_text = " > ".join(hierarchy_stack)
            chunks.append(make_chunk(metadata, text, "header", h_text, url, title))
            return True

        # 4. Đoạn văn / div chỉ lấy nếu không có con đặc biệt
        if elem.name in ["p", "div", "section", "article"]:
            if has_processed_child or elem.get("data-processed") or elem.find(attrs={"data-processed": "true"}):
                return True
            text = clean_text(elem.get_text())
            if 15 < len(text) < 3000:
                h_text = " > ".join(hierarchy_stack) or title
                chunks.append(make_chunk(metadata, text, "paragraph", h_text, url, title))
            return True

        return has_processed_child

    # Bắt đầu duyệt
    for el in main.descendants:
        if getattr(el, "name", None):
            process(el)

    return chunks

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/thuong_tru.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(THUONG_TRU_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(THUONG_TRU_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục đăng ký thường trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/tam_tru.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(TAM_TRU_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(TAM_TRU_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục đăng ký,gia hạn, xóa đăng ký tạm trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/thuong_tru_bca.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(THUONG_TRU_BCA_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(THUONG_TRU_BCA_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục đăng ký thường trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/tam_tru_bca.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(TAM_TRU_BCA_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(TAM_TRU_BCA_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục đăng ký,gia hạn, xóa đăng ký tạm trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/khai_bao_thong_tin.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(KHAI_BAO_THONG_TIN_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(KHAI_BAO_THONG_TIN_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục khai báo thông tin về cư trú đối với người chưa đủ điều kiện đăng ký thường trú, đăng ký tạm trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/dieu_chinh_thong_tin_cu_tru.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(DIEU_CHINH_THONG_TIN_CU_TRU_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(DIEU_CHINH_THONG_TIN_CU_TRU_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục điều chỉnh thông tin về cư trú trong Cơ sở dữ liệu về cư trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/tam_vang.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(KHAI_BAO_TAM_VANG_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(KHAI_BAO_TAM_VANG_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục khai báo tạm vắng",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/tach_ho.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(TACH_HO_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(TACH_HO_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục tách hộ",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
from urllib.parse import urlparse
from datetime import date

# ================== CẤU HÌNH ==================
DATA_FOLDER = "/content/drive/MyDrive/RAG"
OUTPUT_FILE = f"{DATA_FOLDER}/luu_tru.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# ================== CRAWL + CHUNK ==================
all_chunks = []

for idx, item in enumerate(LUU_TRU_URLS, start=1):
    url = item["url"]
    procedure_code = item["procedure_code"]

    print(f"🔹 ({idx}/{len(LUU_TRU_URLS)}) Đã crawl: {procedure_code}")

    metadata = {
        "procedure_code": procedure_code,
        "category": "Thủ tục thông báo lưu trú",
        "official_announce": "68/2020/QH14 ngày 13/11/2020",
        "is_entire": True
    }

    try:
        chunks = crawl_and_chunk(metadata, url, HEADERS)
        all_chunks.extend(chunks)
        print(f"   ✅ Thu được {len(chunks)} chunks")
    except Exception as e:
        print(f"   ❌ Lỗi crawl {procedure_code}: {e}")

# ================== LƯU FILE CHUNG ==================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT!")
print(f"📄 File: {OUTPUT_FILE}")
print(f"📦 Tổng số chunk: {len(all_chunks)}")

import json
import re
import unicodedata
import hashlib

# =========================
# CẤU HÌNH FILE
# =========================
FILES = [
    (f"{DATA_FOLDER}/thuong_tru.json", f"{DATA_FOLDER}/thuong_tru_normalized.json"),
    (f"{DATA_FOLDER}/tam_tru.json", f"{DATA_FOLDER}/tam_tru_normalized.json"),
    (f"{DATA_FOLDER}/thuong_tru_bca.json", f"{DATA_FOLDER}/thuong_tru_bca_normalized.json"),
    (f"{DATA_FOLDER}/tam_tru_bca.json", f"{DATA_FOLDER}/tam_tru_bca_normalized.json"),
    (f"{DATA_FOLDER}/khai_bao_thong_tin.json", f"{DATA_FOLDER}/khai_bao_thong_tin_normalized.json"),
    (f"{DATA_FOLDER}/dieu_chinh_thong_tin_cu_tru.json", f"{DATA_FOLDER}/dieu_chinh_thong_tin_cu_tru_normalized.json"),
    (f"{DATA_FOLDER}/tam_vang.json", f"{DATA_FOLDER}/tam_vang_normalized.json"),
    (f"{DATA_FOLDER}/tach_ho.json", f"{DATA_FOLDER}/tach_ho_normalized.json"),
    (f"{DATA_FOLDER}/luu_tru.json", f"{DATA_FOLDER}/luu_tru_normalized.json"),
]

# =========================
# HÀM CHUẨN HÓA TEXT
# =========================
def normalize_text(text):
    if not text:
        return ""
    text = unicodedata.normalize("NFC", text)  # chuẩn unicode tiếng Việt
    text = re.sub(r"\s+", " ", text)            # bỏ khoảng trắng dư
    return text.strip()

# =========================
# HÀM TẠO KEY LOẠI TRÙNG
# =========================
def make_dedup_key(chunk):
    base = (
        chunk.get("url", "") +
        chunk.get("hierarchy", "") +
        chunk.get("content_text", "")
    )
    return hashlib.md5(base.encode("utf-8")).hexdigest()

# =========================
# HÀM LÀM SẠCH + CHUẨN HÓA FILE
# =========================
def clean_and_normalize_file(input_file, output_file):
    with open(input_file, encoding="utf-8") as f:
        chunks = json.load(f)

    cleaned_chunks = []
    seen = set()

    for chunk in chunks:
        content = normalize_text(chunk.get("content_text", ""))

        # ❌ bỏ chunk rác / quá ngắn
        if len(content) < 1:
            continue

        hierarchy = normalize_text(chunk.get("hierarchy", ""))
        if not hierarchy:
            hierarchy = normalize_text(chunk.get("title", "Không rõ mục"))

        chunk["content_text"] = content
        chunk["hierarchy"] = hierarchy

        # chuẩn hóa metadata
        if "metadata" in chunk:
            for k, v in chunk["metadata"].items():
                if isinstance(v, str):
                    chunk["metadata"][k] = normalize_text(v)

        # ❌ loại trùng
        dedup_key = make_dedup_key(chunk)
        if dedup_key in seen:
            continue

        seen.add(dedup_key)
        cleaned_chunks.append(chunk)

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(cleaned_chunks, f, ensure_ascii=False, indent=2)

    print(f"✅ {input_file}")
    print(f"   Trước: {len(chunks)} chunks")
    print(f"   Sau  : {len(cleaned_chunks)} chunks\n")

# =========================
# CHẠY CHO 9 FILE
# =========================
for raw_file, normalized_file in FILES:
    clean_and_normalize_file(raw_file, normalized_file)

print("᾿ HOÀN TẤT CHUẨN HÓA 9 FILE")

FILES = [
    f"{DATA_FOLDER}/thuong_tru_normalized.json",
    f"{DATA_FOLDER}/tam_tru_normalized.json",
    f"{DATA_FOLDER}/thuong_tru_bca_normalized.json",
    f"{DATA_FOLDER}/tam_tru_bca_normalized.json",
    f"{DATA_FOLDER}/khai_bao_thong_tin_normalized.json",
    f"{DATA_FOLDER}/dieu_chinh_thong_tin_cu_tru_normalized.json",
    f"{DATA_FOLDER}/tam_vang_normalized.json",
    f"{DATA_FOLDER}/tach_ho_normalized.json",
    f"{DATA_FOLDER}/luu_tru_normalized.json"
]

OUTPUT_FILE = f"{DATA_FOLDER}/all_procedures_normalized.json"

all_chunks = []

# =========================
# GỘP DỮ LIỆU
# =========================
for file in FILES:
    with open(file, encoding="utf-8") as f:
        chunks = json.load(f)
        all_chunks.extend(chunks)
        print(f"📥 {file}: {len(chunks)} chunks")

# =========================
# LƯU FILE CHUNG
# =========================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT GỘP FILE")
print(f"📦 Tổng số chunk: {len(all_chunks)}")
print(f"📁 File xuất ra: {OUTPUT_FILE}")

!pip install -U sentence-transformers torch accelerate

JSON_FILE = [
    "/content/drive/MyDrive/RAG/all_procedures_normalized.json"
]
COLLECTION_NAME = "dichvucong_rag"
EMBEDDING_MODEL = "BAAI/bge-m3"

embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name=EMBEDDING_MODEL
)

client = chromadb.PersistentClient(path="./chroma_db")
collection = client.get_or_create_collection(
    name=COLLECTION_NAME,
    embedding_function=embedding_function
)

with open(JSON_FILE[0], "r", encoding="utf-8") as f:
    data = json.load(f)

ids = []
documents = []
metadatas = []

for idx, item in enumerate(data):
    ids.append(item["id"])
    documents.append(item["content_text"])

    meta = item.get("metadata", {}).copy()  # lấy hết metadata cũ

    meta.update({
        "url": item["url"],
        "title": item["title"],
        "hierarchy": item["hierarchy"],
        "chunk_type": item["chunk_type"],
        "domain": item["metadata"].get("source_domain", "unknown"),
    })

    metadatas.append(meta)

print(len(data))

collection.add(
    ids=ids,
    documents=documents,
    metadatas=metadatas
)

print(f"Đã đẩy thành công {len(data)} chunks vào Chroma!")

API_KEY = "AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk"

genai.configure(api_key=API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash')

# ==============================
# TRUY VẤN
# ==============================
query = "Đăng ký thường trú?"

results = collection.query(
    query_texts=[query],
    n_results=6,
    include=["documents", "metadatas", "distances"]
)

# ==============================
# HIỂN THỊ CÁC CHUNK ĐƯỢC RETRIEVAL
# ==============================
print("\n📌 KẾT QUẢ RETRIEVAL:")
for i, (doc, meta, dist) in enumerate(zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0]
    ), start=1):

    hierarchy_val = meta.get("hierarchy", meta.get("title", "Không rõ mục"))
    url_val = meta.get("url", "Không rõ nguồn")

    print(f"\n--- Chunk {i} ---")
    print(f"Distance: {dist}")
    print(f"Hierarchy/Title: {hierarchy_val}")
    print(f"URL: {url_val}")
    print("Nội dung:")
    print(doc)

# ==============================
# TẠO CONTEXT CHO PROMPT
# ==============================
context_parts = []
for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
    hierarchy_val = meta.get("hierarchy", meta.get("title", "Không rõ mục"))
    url_val = meta.get("url", "Không rõ nguồn")

    context_parts.append(
        f"[{hierarchy_val}]\n{doc}\n(Nguồn: {url_val})"
    )

context = "\n\n".join(context_parts)

# ==============================
# PROMPT RAG (SIẾT NGHIÊM)
# ==============================
prompt = f"""
Bạn là trợ lý tư vấn thủ tục hành chính công của Việt Nam.

PHẠM VI ÁP DỤNG:
- Chỉ tư vấn các nội dung LIÊN QUAN ĐẾN thủ tục đăng ký thường trú.
- Các nội dung ngoài phạm vi này không thuộc chức năng của hệ thống.

NGUYÊN TẮC BẮT BUỘC:
- Chỉ sử dụng thông tin có trong CONTEXT bên dưới.
- Tuyệt đối KHÔNG sử dụng kiến thức bên ngoài.
- KHÔNG suy diễn, KHÔNG tự bổ sung.

CÁCH TRẢ LỜI:
- Trả lời ngắn gọn, đúng trọng tâm câu hỏi.
- Có thể tổng hợp nhiều đoạn trong CONTEXT nếu cùng mô tả một nội dung.
- Nếu là danh sách, trình bày bằng gạch đầu dòng hoặc đánh số.

TRƯỜNG HỢP KHÔNG ĐỦ DỮ LIỆU:
Nếu CONTEXT không chứa thông tin để trả lời,
chỉ được trả lời đúng một câu sau (không thêm, không bớt):

"Không tìm thấy thông tin phù hợp trong dữ liệu hiện có."

======================
CONTEXT:
{context}
======================
"""

!conda create -n rag_env python=3.10
!conda activate rag_env
!pip install streamlit
!streamlit run app.py

!pip install streamlit
!pip install google-generativeai
!pip install torch torchvision torchaudio
!pip install sentence-transformers
!pip install beautifulsoup4 requests

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import google.generativeai as genai
# genai.configure(api_key="AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk")
# 
# import streamlit as st
# import json
# import os
# import chromadb
# from chromadb.utils import embedding_functions
# from sentence_transformers import SentenceTransformer
# import google.generativeai as genai
# 
# # Configure Gemini API key (thay bằng key thật của bạn từ Google AI Studio)
# genai.configure(api_key="AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk")
# 
# # ================= CẤU HÌNH =================
# JSON_FILE = "/content/drive/MyDrive/RAG/all_procedures_normalized.json"  # Đường dẫn file JSON (sau chunk rule-based)
# CHROMA_DB_PATH = "chroma_db"
# COLLECTION_NAME = "dichvucong_rag"
# GEMINI_MODEL = "gemini-2.5-flash"
# 
# @st.cache_resource
# def get_embedding_function():
#     EMBEDDING_MODEL = "BAAI/bge-m3"  # Model embedding tiếng Việt
#     embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name=EMBEDDING_MODEL)
#     return embedding_function
# 
# @st.cache_resource
# def load_collection():
#     chroma_client = chromadb.PersistentClient(path=CHROMA_DB_PATH)
#     embedding_func = get_embedding_function()
# 
#     try:
#         collection = chroma_client.get_collection(
#             name=COLLECTION_NAME,
#             embedding_function=embedding_func  # cần để query đúng
#         )
#         st.success(f"Collection '{COLLECTION_NAME}' đã load từ {CHROMA_DB_PATH}")
#     except Exception as e:
#         st.error(f"Không tìm thấy collection '{COLLECTION_NAME}' trong {CHROMA_DB_PATH}: {e}")
#         collection = None
# 
#     return collection
# # --- Load collection 1 lần ---
# collection = load_collection()
# 
# def query_rag(query: str, chat_history: list, top_k: int):
#     # Retrieval với top_k động
#     results = collection.query(
#         query_texts=[query],
#         n_results=top_k,
#         include=["documents", "metadatas", "distances"]
#     )
# 
#     context_parts = []
#     for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
#         context_parts.append(f"[{meta['hierarchy']}]\\n{doc}\\n(Nguồn: {meta['url']})")
# 
#     context = "\\n\\n".join(context_parts)
# 
#     prompt = f"""
#     Bạn là trợ lý tư vấn thủ tục hành chính đăng ký thường trú tại Việt Nam. Trả lời ngắn gọn, chính xác, dễ hiểu, có dẫn nguồn. Chỉ trả lời dựa trên context, không thêm thông tin ngoài.
# 
#     Context:
#     {context}
# 
#     Câu hỏi: {query}
# 
#     Trả lời bằng tiếng Việt, có đánh số nếu là danh sách, và trích dẫn nguồn rõ ràng (tên block, URL):
#     """
# 
#     model = genai.GenerativeModel(GEMINI_MODEL)
#     response = model.generate_content(prompt, stream=True)
# 
#     return response
# 
# # Giao diện chính
# st.set_page_config(page_title="Chatbot tư vấn thủ tục hành chính đăng ký thường trú", layout="centered")
# st.title("Chatbot tư vấn thủ tục hành chính đăng ký thường trú")
# 
# # Sidebar với top-k slider và thông tin
# with st.sidebar:
#     st.header("Cài đặt")
#     top_k = st.slider("Top-k retrieval (số chunks lấy về)", min_value=1, max_value=10, value=3, step=1)
#     st.header("Thông tin")
#     st.write(f"Vector DB: {COLLECTION_NAME}")
#     st.write(f"Số chunk: {collection.count() if collection else 0}")
#     st.write(f"Model LLM: {GEMINI_MODEL}")
#     st.write("Embedding: BAAI/bge-m3 (tối ưu tiếng Việt)")
#     st.caption("Dữ liệu load từ file JSON. Nếu lỗi, kiểm tra đường dẫn JSON_FILE.")
# 
# # Khởi tạo lịch sử chat
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# # Hiển thị lịch sử chat
# for message in st.session_state.messages:
#     with st.chat_message(message["role"]):
#         st.markdown(message["content"])
# 
# # Input từ user
# if prompt := st.chat_input("Hỏi về đăng ký thường trú (ví dụ: Đăng ký thường trú cần gì?)"):
#     # Thêm tin nhắn user
#     st.session_state.messages.append({"role": "user", "content": prompt})
#     with st.chat_message("user"):
#         st.markdown(prompt)
# 
#     # Gọi RAG với top_k từ slider và stream response
#     with st.chat_message("assistant"):
#         message_placeholder = st.empty()
#         full_response = ""
# 
#         try:
#             response = query_rag(prompt, st.session_state.messages, top_k)
#             for chunk in response:
#                 if chunk.text:
#                     full_response += chunk.text
#                     message_placeholder.markdown(full_response + " ")
#             message_placeholder.markdown(full_response)
#         except Exception as e:
#             full_response = f"Lỗi khi gọi Gemini: {str(e)}"
#             message_placeholder.error(full_response)
# 
#     # Lưu response vào lịch sử
#     st.session_state.messages.append({"role": "assistant", "content": full_response})
# # Dán toàn bộ code trên vào đây
#

!sed -n '1,200p' app.py

!pip install openai streamlit

# Để khắc phục lỗi StreamlitSecretNotFoundError:
!mkdir -p .streamlit
!echo 'OPENAI_API_KEY="AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk"' > .streamlit/secrets.toml
#    (Nhớ thay YOUR_API_KEY bằng khóa OpenAI API thực tế của bạn)
# Dòng này chỉ là hướng dẫn, không phải code để chạy.

import streamlit as st
from openai import OpenAI

st.title("ChatGPT-like clone")

# Set OpenAI API key from Streamlit secrets
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

# Set a default model
if "openai_model" not in st.session_state:
    st.session_state["openai_model"] = "gpt-3.5-turbo"

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat messages from history on app rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Accept user input
if prompt := st.chat_input("What is up?"):
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})
    # Display user message in chat message container
    with st.chat_message("user"):
        st.markdown(prompt)

    # Display assistant response in chat message container
    with st.chat_message("assistant"):
        stream = client.chat.completions.create(
            model=st.session_state["openai_model"],
            messages=[
                {"role": m["role"], "content": m["content"]}
                for m in st.session_state.messages
            ],
            stream=True,
        )
        response = st.write_stream(stream)
    st.session_state.messages.append({"role": "assistant", "content": response})

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com

query ="Có bao nhiêu cách thực hiện đăng ký thường trú?"

results = collection.query(
        query_texts=[query],
        n_results=6,
        include=["documents", "metadatas", "distances"]
    )

# ==============================
# HIỂN THỊ CÁC CHUNK ĐƯỢC RETRIEVAL
# ==============================
print("\n📌 KẾT QUẢ RETRIEVAL:")
for i, (doc, meta, dist) in enumerate(zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0]
    ), start=1):

    hierarchy_val = meta.get('hierarchy', meta.get('title', 'Không rõ mục'))
    url_val = meta.get('url', 'Không rõ nguồn')

    print(f"\n--- Chunk {i} ---")
    print(f"Distance: {dist}")
    print(f"Hierarchy/Title: {hierarchy_val}")
    print(f"URL: {url_val}")
    print("Nội dung:")
    print(doc)

# ==============================
# TẠO CONTEXT CHO PROMPT
# ==============================
context_parts = []
for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
    hierarchy_val = meta.get('hierarchy', meta.get('title', 'Không rõ mục'))
    url_val = meta.get('url', 'Không rõ nguồn')
    context_parts.append(f"[{hierarchy_val}]\n{doc}\n(Nguồn: {url_val})")

context = "\n\n".join(context_parts)

prompt = f"""
Bạn là trợ lý tư vấn thủ tục hành chính công Việt Nam.

PHẠM VI ÁP DỤNG:
- Ưu tiên tư vấn các thủ tục hành chính liên quan đến hỗ trợ cư trú.
- Nếu CONTEXT không đề cập rõ độ tuổi nhưng nội dung thuộc thủ tục thường áp dụng cho trẻ em,
  bạn được phép trả lời dựa trên thông tin hiện có và nêu rõ phạm vi áp dụng nếu được đề cập.

NGUYÊN TẮC TRẢ LỜI:
- Chỉ sử dụng thông tin có trong CONTEXT bên dưới.
- Không sử dụng kiến thức bên ngoài.
- Không tự bổ sung thông tin không có trong CONTEXT.

CÁCH TRẢ LỜI:
- Chỉ trả lời các nội dung LIÊN QUAN TRỰC TIẾP đến câu hỏi.
- Có thể tổng hợp nhiều đoạn trong CONTEXT nếu chúng cùng mô tả một thủ tục.
- Trình bày ngắn gọn, rõ ràng, đúng trọng tâm.

TRƯỜNG HỢP KHÔNG TRẢ LỜI:
Chỉ trả lời đúng câu sau nếu:
- CONTEXT hoàn toàn không chứa thông tin liên quan đến câu hỏi.

Câu trả lời trong trường hợp này PHẢI CHÍNH XÁC:
"Không tìm thấy thông tin phù hợp trong dữ liệu hiện có."

YÊU CẦU ĐỊNH DẠNG:
- Trả lời bằng tiếng Việt.
- Nếu có nhiều ý, trình bày bằng gạch đầu dòng hoặc đánh số.
- Giữ nguyên trích dẫn nguồn nếu có trong CONTEXT.

======================
CONTEXT:
{context}
======================

CÂU HỎI:
{query}

CÂU TRẢ LỜI:
"""

try:
    response = model.generate_content(prompt)
    print("\n📝 TRẢ LỜI CỦA HỆ THỐNG:")
    print(response.text)
except Exception as e:
    error_msg = str(e).lower()

    if "quota" in error_msg or "limit" in error_msg or "exceeded" in error_msg or "429" in error_msg:
        print("⚠️ Phiên làm việc hiện tại đã kết thúc do đã sử dụng hết số lượt câu hỏi. Vui lòng chờ sang phiên tiếp theo để tiếp tục tra cứu thông tin.")
    else:
        print("⚠️ Hệ thống đang gặp sự cố khi xử lý câu hỏi. Vui lòng thử lại sau.")

!conda create -n rag_env python=3.10
!conda activate rag_env
!pip install streamlit
!streamlit run app.py

!pip install streamlit
!pip install google-generativeai
!pip install torch torchvision torchaudio
!pip install sentence-transformers
!pip install beautifulsoup4 requests

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import google.generativeai as genai
# genai.configure(api_key="AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk")
# 
# import streamlit as st
# import json
# import os
# import chromadb
# from chromadb.utils import embedding_functions
# from sentence_transformers import SentenceTransformer
# import google.generativeai as genai
# 
# # Configure Gemini API key (thay bằng key thật của bạn từ Google AI Studio)
# genai.configure(api_key="AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk")
# 
# # ================== CẤU HÌNH ==================
# JSON_FILE = "/content/drive/MyDrive/RAG/all_procedures_normalized.json"  # Đường dẫn file JSON (sau chunk rule-based)
# CHROMA_DB_PATH = "chroma_db"  # Thư mục lưu vector DB
# COLLECTION_NAME = "dichvucong_rag"
# GEMINI_MODEL = "gemini-2.5-flash"  # Hoặc "gemini-1.5-pro"
# 
# @st.cache_resource
# def get_embedding_function():
#     EMBEDDING_MODEL = "BAAI/bge-m3"  # Model embedding tiếng Việt
#     embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name=EMBEDDING_MODEL)
#     return embedding_function
# 
# @st.cache_resource
# def load_collection():
#     chroma_client = chromadb.PersistentClient(path=CHROMA_DB_PATH)
#     embedding_func = get_embedding_function()
# 
#     try:
#         collection = chroma_client.get_collection(
#             name=COLLECTION_NAME,
#             embedding_function=embedding_func  # cần để query đúng
#         )
#         st.success(f"Collection '{COLLECTION_NAME}' đã load từ {CHROMA_DB_PATH}")
#     except Exception as e:
#         st.error(f"Không tìm thấy collection '{COLLECTION_NAME}' trong {CHROMA_DB_PATH}: {e}")
#         collection = None
# 
#     return collection
# # --- Load collection 1 lần ---
# collection = load_collection()
# 
# def query_rag(query: str, chat_history: list, top_k: int):
#     # Retrieval với top_k động
#     results = collection.query(
#         query_texts=[query],
#         n_results=top_k,
#         include=["documents", "metadatas", "distances"]
#     )
# 
#     context_parts = []
#     for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
#         context_parts.append(f"[{meta['hierarchy']}]\\n{doc}\\n(Nguồn: {meta['url']})")
# 
#     context = "\\n\\n".join(context_parts)
# 
#     prompt = f"""
#     Bạn là trợ lý tư vấn thủ tục hành chính về cư trú tại Việt Nam. Trả lời ngắn gọn, chính xác, dễ hiểu, có dẫn nguồn. Chỉ trả lời dựa trên context, không thêm thông tin ngoài.
# 
#     Context:
#     {context}
# 
#     Câu hỏi: {query}
# 
#     Trả lời bằng tiếng Việt, có đánh số nếu là danh sách, và trích dẫn nguồn rõ ràng (tên block, URL):
#     """
# 
#     model = genai.GenerativeModel(GEMINI_MODEL)
#     response = model.generate_content(prompt, stream=True)
# 
#     return response
# 
# # Giao diện chính
# st.set_page_config(page_title="Chatbot tư vấn thủ tục hành chính về cư trú", layout="centered")
# st.title("Chatbot tư vấn thủ tục hành chính về cư trú")
# 
# # Sidebar với top-k slider và thông tin
# with st.sidebar:
#     st.header("Cài đặt")
#     top_k = st.slider("Top-k retrieval (số chunks lấy về)", min_value=1, max_value=10, value=3, step=1)
#     st.header("Thông tin")
#     st.write(f"Vector DB: {COLLECTION_NAME}")
#     st.write(f"Số chunk: {collection.count() if collection else 0}")
#     st.write(f"Model LLM: {GEMINI_MODEL}")
#     st.write("Embedding: BAAI/bge-m3 (tối ưu tiếng Việt)")
#     st.caption("Dữ liệu load từ file JSON. Nếu lỗi, kiểm tra đường dẫn JSON_FILE.")
# 
# # Khởi tạo lịch sử chat
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# # Hiển thị lịch sử chat
# for message in st.session_state.messages:
#     with st.chat_message(message["role"]):
#         st.markdown(message["content"])
# 
# # Input từ user
# if prompt := st.chat_input("Hỏi về thủ tục hành chính về cư trú (ví dụ: Đăng ký thường trú cần gì?)"):
#     # Thêm tin nhắn user
#     st.session_state.messages.append({"role": "user", "content": prompt})
#     with st.chat_message("user"):
#         st.markdown(prompt)
# 
#     # Gọi RAG với top_k từ slider và stream response
#     with st.chat_message("assistant"):
#         message_placeholder = st.empty()
#         full_response = ""
# 
#         try:
#             response = query_rag(prompt, st.session_state.messages, top_k)
#             for chunk in response:
#                 if chunk.text:
#                     full_response += chunk.text
#                     message_placeholder.markdown(full_response + " ")
#             message_placeholder.markdown(full_response)
#         except Exception as e:
#             full_response = f"Lỗi khi gọi Gemini: {str(e)}"
#             message_placeholder.error(full_response)
# 
#     # Lưu response vào lịch sử
#     st.session_state.messages.append({"role": "assistant", "content": full_response})
# # Dán toàn bộ code trên vào đây

!sed -n '1,200p' app.py

!pip install openai streamlit

# Để khắc phục lỗi StreamlitSecretNotFoundError:
!mkdir -p .streamlit
!echo 'OPENAI_API_KEY="AIzaSyC4G5cGpl2XCKmQkAcCl0IEt4tzp_lU3mk"' > .streamlit/secrets.toml
#    (Nhớ thay YOUR_API_KEY bằng khóa OpenAI API thực tế của bạn)
# Dòng này chỉ là hướng dẫn, không phải code để chạy.

import streamlit as st
from openai import OpenAI

st.title("ChatGPT-like clone")

# Set OpenAI API key from Streamlit secrets
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

# Set a default model
if "openai_model" not in st.session_state:
    st.session_state["openai_model"] = "gpt-3.5-turbo"

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat messages from history on app rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Accept user input
if prompt := st.chat_input("What is up?"):
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})
    # Display user message in chat message container
    with st.chat_message("user"):
        st.markdown(prompt)

    # Display assistant response in chat message container
    with st.chat_message("assistant"):
        stream = client.chat.completions.create(
            model=st.session_state["openai_model"],
            messages=[
                {"role": m["role"], "content": m["content"]}
                for m in st.session_state.messages
            ],
            stream=True,
        )
        response = st.write_stream(stream)
    st.session_state.messages.append({"role": "assistant", "content": response})

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt &
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com

"""# Task
The `FILES` list in cell `LWEIZI6G2-Bc` contains extra closing parentheses at the end of each file path string, causing a `SyntaxError`. I will remove these extra parentheses and then re-execute the cell to correctly merge the normalized JSON files.

```python
FILES = [
    f"{DATA_FOLDER}/thuong_tru_normalized.json",
    f"{DATA_FOLDER}/tam_tru_normalized.json",
    f"{DATA_FOLDER}/thuong_tru_bca_normalized.json",
    f"{DATA_FOLDER}/tam_tru_bca_normalized.json",
    f"{DATA_FOLDER}/khai_bao_thong_tin_normalized.json",
    f"{DATA_FOLDER}/dieu_chinh_thong_tin_cu_tru_normalized.json",
    f"{DATA_FOLDER}/tam_vang_normalized.json",
    f"{DATA_FOLDER}/tach_ho_normalized.json",
    f"{DATA_FOLDER}/luu_tru_normalized.json"
]

OUTPUT_FILE = f"{DATA_FOLDER}/all_procedures_normalized.json"

all_chunks = []

# =========================
# GỘP DỮ LIỆU
# =========================
for file in FILES:
    with open(file, encoding="utf-8") as f:
        chunks = json.load(f)
        all_chunks.extend(chunks)
        print(f"📥 {file}: {len(chunks)} chunks")

# =========================
# LƯU FILE CHUNG
# =========================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT GỘP FILE")
print(f"📦 Tổng số chunk: {len(all_chunks)}")
print(f"📁 File xuất ra: {OUTPUT_FILE}")
```

## Remove extra parentheses in FILES list

### Subtask:
Correct the `FILES` list in cell `LWEIZI6G2-Bc` by removing extraneous closing parentheses from each file path string.

**Reasoning**:
The subtask requires correcting the `FILES` list in cell `LWEIZI6G2-Bc` by removing extraneous closing parentheses. I will generate a code block to update the `FILES` list with the corrected file paths.
"""

FILES = [
    f"{DATA_FOLDER}/thuong_tru_normalized.json",
    f"{DATA_FOLDER}/tam_tru_normalized.json",
    f"{DATA_FOLDER}/thuong_tru_bca_normalized.json",
    f"{DATA_FOLDER}/tam_tru_bca_normalized.json",
    f"{DATA_FOLDER}/khai_bao_thong_tin_normalized.json",
    f"{DATA_FOLDER}/dieu_chinh_thong_tin_cu_tru_normalized.json",
    f"{DATA_FOLDER}/tam_vang_normalized.json",
    f"{DATA_FOLDER}/tach_ho_normalized.json",
    f"{DATA_FOLDER}/luu_tru_normalized.json"
]

OUTPUT_FILE = f"{DATA_FOLDER}/all_procedures_normalized.json"

all_chunks = []

# =========================
# GỘP DỮ LIỆU
# =========================
for file in FILES:
    with open(file, encoding="utf-8") as f:
        chunks = json.load(f)
        all_chunks.extend(chunks)
        print(f"📥 {file}: {len(chunks)} chunks")

# =========================
# LƯU FILE CHUNG
# =========================
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(all_chunks, f, ensure_ascii=False, indent=2)

print("\n🎉 HOÀN TẤT GỘP FILE")
print(f"📦 Tổng số chunk: {len(all_chunks)}")
print(f"📁 File xuất ra: {OUTPUT_FILE}")

"""## Summary:

### Data Analysis Key Findings
*   The initial `SyntaxError` was caused by extraneous closing parentheses in the file path strings within the `FILES` list.
*   The issue was resolved by removing these extra parentheses, allowing the script to execute successfully.
*   Nine normalized JSON files were successfully processed and merged:
    *   `thuong_tru_normalized.json`: 7 chunks
    *   `tam_tru_normalized.json`: 21 chunks
    *   `thuong_tru_bca_normalized.json`: 30 chunks
    *   `tam_tru_bca_normalized.json`: 32 chunks
    *   `khai_bao_thong_tin_normalized.json`: 70 chunks
    *   `dieu_chinh_thong_tin_cu_tru_normalized.json`: 43 chunks
    *   `tam_vang_normalized.json`: 31 chunks
    *   `tach_ho_normalized.json`: 10 chunks
    *   `luu_tru_normalized.json`: 1069 chunks
*   A total of 1313 chunks were merged into the output file `all_procedures_normalized.json`.

### Insights or Next Steps
*   The successfully merged data in `all_procedures_normalized.json` is now ready for subsequent analysis or processing steps.
*   Implementing a more robust input validation or sanitization process for file paths could prevent similar `SyntaxError` issues in the future.

"""